/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warteg.lalapan.gui;

/**
 *
 * @author fath
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisLalapan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lalapanAyam = new javax.swing.JRadioButton();
        jenisLalapan.add(lalapanAyam);
        lalapanLele = new javax.swing.JRadioButton();
        lalapanBebek = new javax.swing.JRadioButton();
        lblLalapan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jenis Lalapan");

        lalapanAyam.setText("Ayam");
        lalapanAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanAyamActionPerformed(evt);
            }
        });

        lalapanLele.setText("Lele");
        lalapanLele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanLeleActionPerformed(evt);
            }
        });

        lalapanBebek.setText("Bebek");
        lalapanBebek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanBebekActionPerformed(evt);
            }
        });

        lblLalapan.setText("pilihan anda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lalapanAyam)
                        .addGap(42, 42, 42)
                        .addComponent(lalapanLele)
                        .addGap(42, 42, 42)
                        .addComponent(lalapanBebek))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(lblLalapan)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalapanAyam)
                    .addComponent(lalapanLele)
                    .addComponent(lalapanBebek))
                .addGap(30, 30, 30)
                .addComponent(lblLalapan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lalapanLeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanLeleActionPerformed
        // TODO add your handling code here:
        if (lalapanLele.isSelected()) {
            lblLalapan.setText("Anda Memilih Lalapan " + lalapanLele.getText());
        }
    }//GEN-LAST:event_lalapanLeleActionPerformed

    private void lalapanBebekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanBebekActionPerformed
        // TODO add your handling code here:
        if (lalapanBebek.isSelected()) {
            lblLalapan.setText("Anda Memilih Lalapan " + lalapanBebek.getText());
        }
    }//GEN-LAST:event_lalapanBebekActionPerformed

    private void lalapanAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanAyamActionPerformed
        // TODO add your handling code here:
        if (lalapanAyam.isSelected()) {
            lblLalapan.setText("Anda Memilih Lalapan " + lalapanAyam.getText());
        }
    }//GEN-LAST:event_lalapanAyamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.ButtonGroup jenisLalapan;
    private javax.swing.JRadioButton lalapanAyam;
    private javax.swing.JRadioButton lalapanBebek;
    private javax.swing.JRadioButton lalapanLele;
    private javax.swing.JLabel lblLalapan;
    // End of variables declaration//GEN-END:variables
}
